packages:
  - packages/*

catalogMode: prefer

catalog:
  "@earendil-works/pi-ai": ^0.80.10
  "@earendil-works/pi-coding-agent": ^0.80.10
  "@earendil-works/pi-tui": ^0.80.10
  "@mozilla/readability": ^0.6.0
  "@types/node": ^26.1.1
  "@types/turndown": ^5.0.6
  diff: ^8.0.4
  linkedom: ^0.18.12
  ts-syntax-highlighter: ^0.2.5
  turndown: ^7.2.4
  typebox: ^1.0.64
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  "@google/genai": set this to true or false
  esbuild: true
  protobufjs: set this to true or false
